service:
  type: NodePort
cluster:
  enabled: false
pulsar:
  enabled: false

etcd:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "openebs-hostpath"
    size: 10Gi

minio:
  mode: standalone
  persistence:
    enabled: true
    storageClass: "openebs-hostpath"
    size: 20Gi

standalone:
  persistence:
    enabled: true
    storageClass: "openebs-hostpath"
    size: 50Gi
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
